### ISSUE TITLE
ArangoDeploymentTasks

### ISSUE THREAD

**Issue by ewoutp** [arangodb/kube-arangodb#34]
This issues is intended to track tasks needed for `ArangoDeployment` resource.

- [x] CRD creation
  - [x] Move CRD creation to YAML
- [x] Create Service's
  - [x] Session stickyness (cursor)
  - [x] Other service types? `LoadBalancer`, `NodePort`
- [x] Create Pod's
  - [x] Detect ArangoDB version of image and use explicity image-ID
  - [x] Only init UUID for new members. On restart, init by checking the UUID.
- [x] Create PersistentVolumeClaim's
- [ ] Resilience
  - [x] Detect pod not being scheduled for a long time
  - [x] Detect pod being not ready for a long time
  - [x] Detect pod being restarted often (recently)
  - [ ] Deeper inspection of database/cluster health
- [x] Scale up/down
  - [x] Integrate with scaling controls in web-UI 
- [ ] Rolling update
  - [x] Upgrade to newer/older version
  - [ ] Change server arguments (rolling update) (#189)
  - [x] Certificate renewal
  - [ ] JWT token renewal (#188)
- [x] Authentication support
- [x] TLS support
  - [x] Decide on turning on TLS by default
  - [x] Certificate renewal
  - [x] Certificate renewal when TLS settings are updated (e.g. altNames)
  - [ ] Test & document CA installation on Windows (#192)
  - [x] Test & document CA installation on Mac
  - [ ] Test & document CA installation on Linux (#192)
- [x] DC2DC support
- [x] Recover from broken nodes
- [ ] Check if there is specified (or default) StorageClass exists (#191)
- [x] Unit tests
- [x] Integration tests
- [x] Release script

**Comment by ewoutp** [comment]
Closing in favor of individual issues
